name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run tests with Go container
      uses: docker://golang:1.23
      with:
        args: sh -c "go test ./..."

    - name: Set Heroku container stack
      run: |
        curl -n -X PATCH https://api.heroku.com/apps/${{ env.HEROKU_APP_NAME }} \
          -H "Content-Type: application/json" \
          -H "Accept: application/vnd.heroku+json; version=3" \
          -H "Authorization: Bearer $HEROKU_API_KEY" \
          -d '{"build_stack":"container"}'

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Build Docker image
      run: docker build -t $DOCKER_USERNAME/url-shortener:$GITHUB_SHA .

    - name: Push Docker image to DockerHub
      run: docker push $DOCKER_USERNAME/url-shortener:$GITHUB_SHA

    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh

    - name: Deploy to Heroku
      run: |
        echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com
        docker tag $DOCKER_USERNAME/url-shortener:$GITHUB_SHA registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web
        docker push registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web
        heroku container:release web --app ${{ env.HEROKU_APP_NAME }}